name: Publish to Maven Pages

on:
  workflow_run:
    workflows: ["release"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & publish to local Maven repo directory
        run: ./gradlew --no-daemon clean publish

      - name: Deploy built Maven repo to jmilthedude/maven (GitHub Pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: jmilthedude/maven
          publish_dir: build/repo
          publish_branch: main
          keep_files: true