name: Publish to Maven Pages
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build & publish to local dir
        run: ./gradlew --no-daemon publish

      - name: Deploy to jmilthedude/maven repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: jmilthedude/maven
          publish_dir: build/repo
          publish_branch: main
          keep_files: true
