name: release
on:
  push:
    tags:
      - "v*"   # e.g. v1.0.0, v1.0.1
jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew --no-daemon build
      - name: List build outputs
        run: ls -l build/libs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/libs/NinjaConfig-*.jar
            build/libs/NinjaConfig-*-sources.jar